apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: helloservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - helloservice.podtatohead-hardening.public.demo.keptn.sh
  - helloservice
  http:
  - route:
    - destination:
        host: helloservice-canary.podtatohead-hardening.svc.cluster.local
    - destination:
        host: helloservice-primary.podtatohead-hardening.svc.cluster.local
      weight: 100
