apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: helloservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - helloservice.podtatohead-production.svc.cluster.local
  - helloservice
  http:
  - route:
    - destination:
        host: helloservice-canary.podtatohead-production.svc.cluster.local
    - destination:
        host: helloservice-primary.podtatohead-production.svc.cluster.local
      weight: 100
